### ISSUE TITLE
Users can view the letters to type

### ISSUE THREAD

**Issue by gdegas** [gdegas001/typing-test#1]
# Motivation
So that the user can see what he/she is typing

# Tasks
- [x] add a header
- [x] add a line below the header
- [x] write a paragraph element
- [x] input text in the paragraph element
- [x] center my header
- [x] center my paragraph
