### ISSUE TITLE
User can see prompt for current letter.

### ISSUE THREAD

**Issue by gdegas** [gdegas001/typing-test#2]
# Motivation
User can view which letter he/she needs to input on the keyboard

# Tasks
- [ ] create a function to change each letter
- [ ] make a loop to cycle through each letter
- [ ] apply the function to the loop
- [ ] add CSS to change the px of each letter
