### ISSUE TITLE
User can type a letter and get feedback.

### ISSUE THREAD

**Issue by gdegas** [gdegas001/typing-test#3]
# Motivation
The user can see if he/she is typing the same letter

# Tasks
- [ ] create variable to store first letter
- [ ] create event listener that listens for keypress on the document object
- [ ] create if else statement and attach to function in event listener
- [ ] in condition, set keypress event = text content of first letter
